# JackAnalyzer: JackAnalyzer.c
# 	gcc JackAnalyzer.c -o JackAnalyzer
# 	chmod +x JackAnalyzer

# JackTokenizer: JackTokenizer.c
# 	gcc JackTokenizer.c -std=c11 -o JackTokenizer
# 	chmod +x JackTokenizer

CompilationEngine: CompilationEngine.c
	gcc CompilationEngine.c -std=c11 -o CompilationEngine
	chmod +x CompilationEngine
